const BLOG = {
  API_BASE_URL: process.env.API_BASE_URL || 'https://www.notion.so/api/v3',
  NOTION_PAGE_ID: 'a069239ad795825c88bc8150daea3048',
  PSEUDO_STATIC: process.env.NEXT_PUBLIC_PSEUDO_STATIC || false,
  NEXT_REVALIDATE_SECOND: process.env.NEXT_PUBLIC_REVALIDATE_SECOND || 60,
  THEME: process.env.NEXT_PUBLIC_THEME || 'hexo',
  TITLE: 'Elkut的赛博次元档案馆',
  DESCRIPTION: '这里是Elkut的私人观测站，记录笔记、ACG、TRPG与哲学。✨',
  KEYWORDS: 'Notion, 博客, ACG, 二次元, 编程, AI, Elkut, TRPG, 哲学',
  AUTHOR: 'Elkut',
  NICKNAME: 'Elkut',
  BIO: ' 👾 ',
  LINK: 'https://elkut.codes',
  LANG: process.env.NEXT_PUBLIC_LANG || 'zh-CN',
  SINCE: 2024,
  AVATAR: '80f1e224aba27c7c3b9c1bbff12750b2.jpg',
  AVATAR_LINK: '/about',
  HOME_BANNER_IMAGE: '80f1e224aba27c7c3b9c1bbff12750b2.jpg',
  APPEARANCE: process.env.NEXT_PUBLIC_APPEARANCE || 'auto',
  APPEARANCE_DARK_TIME: process.env.NEXT_PUBLIC_APPEARANCE_DARK_TIME || [18, 6],
  HOME_BANNER_STRINGS: [
    '~ Welcome to Elkut\'s Digital Sanctuary ~',
    '这里记录着关于 <b class="text-orange-300">人工智能</b> 的课程笔记...',
    '也保存着 <b class="text-pink-300">TRPG 跑团</b> 的精彩瞬间...',
    '偶尔还会讨论 <b class="text-green-300">独立游戏</b> 与哲学命题...',
    '愿你在我的次元里找到共鸣 ✨'
  ],
  GREETING_WORDS: '~ Welcome to Elkut\'s Digital Sanctuary ~,这里记录着关于人工智能的课程笔记...,也保存着 TRPG 跑团 的精彩瞬间...,偶尔还会讨论独立游戏与哲学命题...,愿你在我的次元里找到共鸣 ✨',
  CUSTOM_MENU: process.env.NEXT_PUBLIC_CUSTOM_MENU || true,
  MENU_CATEGORY: true,
  MENU_TAG: true,
  MENU_ARCHIVE: true,
  MENU_SEARCH: true,
  CONTACT_EMAIL: '',
  CONTACT_GITHUB: '',
  CONTACT_TWITTER: '',
  CONTACT_TELEGRAM: '',
  CONTACT_BILIBILI: '',
  BLOG_FAVICON: process.env.NEXT_PUBLIC_FAVICON || '/favicon.ico',
  BEI_AN: process.env.NEXT_PUBLIC_BEI_AN || '',
  BEI_AN_LINK: 'https://beian.miit.gov.cn/',
  BEI_AN_GONGAN: process.env.NEXT_PUBLIC_BEI_AN_GONGAN || '',
  ENABLE_RSS: process.env.NEXT_PUBLIC_ENABLE_RSS || true,
  CAN_COPY: process.env.NEXT_PUBLIC_CAN_COPY || true,
  LAYOUT_SIDEBAR_REVERSE: process.env.NEXT_PUBLIC_LAYOUT_SIDEBAR_REVERSE || false,
  UUID_REDIRECT: process.env.UUID_REDIRECT || false,
  IS_SITEMAP_AUTO_GENERATED: true,
  ...require('./conf/comment.config'),
  ...require('./conf/contact.config'),
  ...require('./conf/post.config'),
  ...require('./conf/analytics.config'),
  ...require('./conf/image.config'),
  ...require('./conf/font.config'),
  ...require('./conf/right-click-menu'),
  ...require('./conf/code.config'),
  ...require('./conf/animation.config'),
  ...require('./conf/widget.config'),
  ...require('./conf/ad.config'),
  ...require('./conf/plugin.config'),
  ...require('./conf/performance.config'),
  ...require('./conf/layout-map.config'),
  ...require('./conf/notion.config'),
  ...require('./conf/dev.config'),
  CUSTOM_EXTERNAL_JS: [''],
  CUSTOM_EXTERNAL_CSS: ['']
}

module.exports = BLOG
